preload = /home/akumar/.config/hypr/wallpapers/ibm.jpg

wallpaper {
    monitor = DP-1
    path = /home/akumar/.config/hypr/wallpapers/ibm.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/akumar/.config/hypr/wallpapers/ibm.jpg
    fit_mode = cover
}

ipc = true
splash = false
