# Decoration settings

general {
  border_size = 2
  gaps_in = 5
  gaps_out = 5

  col.active_border   = rgba(e1e3e4ff)
  col.inactive_border = rgba(494d64ff)
}

decoration {
  rounding = 0

  active_opacity     = 1.0
  inactive_opacity   = 0.95
  fullscreen_opacity = 1.0

  dim_inactive = false

  shadow {
    enabled = false
  }

  blur {
    enabled = false
  }
}
